---
title: "e0029 Differential Colonization Analysis"
output: html_document
date: "2025-05-21"
---


# Load in packages

```{r, warning=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
library(ggrepel)
library(purrr)
library(patchwork)
library(foreach)
library(forcats)
library(cowplot)
```


# Load in the Household Project dataset

```{r}

household_data <- read.table("C:/Users/anaes/OneDrive/UCI_Spring25/rotation/e0026-e0029-e0030.txt", header = TRUE)

# Divide dataset into separate tables by experiment
e0029 <- filter(household_data, str_detect(household_data$sample, "e0029"))

e0026 <- filter(household_data, str_detect(household_data$sample, "e0026"))

# Extract subject, day, household information
e0029_clean <- e0029 %>%
  mutate(
    subject = str_sub(biosample1, 1, -5),
    day = str_sub(biosample1, -3),
    household = str_sub(biosample1, 1, -6)
  )

# Specify output directory

OUTPUTDIR <- "./e0029_outputs"

# Define color palette

my_colors <- readRDS("C:/Spring-Rotation-2025/scratch/familyColorPalette.rds") 

```



### Get beta diversity


**Create phyloseq object**


```{r}

data <- readRDS("../../data/ps_all.rds")

hp_data_clean <- prune_taxa(taxa_sums(data) > 0, data)

e0026_e0029_obj <- subset_samples(
  hp_data_clean,
  experiment == "e0029" | 
    experiment == "e0026"
)

# e0026_e0029_obj <- subset_samples(e0026_e0029_obj,
#     biosample1 != "blank" &
#     biosample1 != "B-mix" &
#     !grepl("\\+", biosample2))

```


```{r}
# # List the distance-calculation methods to be used.
# distMethods <- c("jsd","bray","jaccard")
# 
# # Write a function to calculate a distance matrix using the specified method
# # and convert the data into tidy format.
# calculateBeta <- function(data, distMethod) {
#   # Calculate the distance matrix using the specified method.
#   betaRaw <- distance(data, method=distMethod)
# 
#   # Convert distance matrix to a dataframe.
#   beta <- as.matrix(betaRaw)
#   beta <- as.data.frame(beta)
#   beta$sample1 <- rownames(beta)
#   # Tidy the dataframe.
#   beta <- beta %>%
# 	pivot_longer(-sample1, names_to="sample2", values_to="value")
#   beta <- beta %>%
# 	filter(sample1 != sample2) %>%
# 	mutate(method=distMethod)
# }
# 
# # Calculate the distance matrix for all of the specified methods on the species abundances.
# # Combine the distance matrices for all methods.
# betaSpecies <- do.call(rbind, lapply(distMethods, function(distMethod) {
#   print(distMethod)
#   calculateBeta(e0026_e0029_obj, distMethod)
# }))
# # Export the distance matrix generated for all of the sample pairs
# # using all of the specified methods.
# write_delim(betaSpecies, paste0("e0026_e0029_speciesBeta.txt.gz"))


```



### JSD between all possible combinations



```{r, warning=FALSE}

beta_diversity <- read_delim("./e0026_e0029_speciesBeta.txt.gz")
data(beta_diversity)


beta_diversity_wide <- beta_diversity %>%
  select(sample1, sample2, method, value) %>%
  pivot_wider(names_from = method, values_from = value)

beta_diversity_wide <- beta_diversity_wide %>%
  filter(!grepl("e0029", sample1), !grepl("e0029", sample2))

```




```{r}

recipients <- c("XBA-029", "XBA-036", "XBA-064", "XDA-029", "XDA-036", "XDA-064", "XEA-029", "XEA-036", "XEA-064", "XKA-029", "XKA-036", "XKA-064")

e0026_filtered <- e0026 %>% 
  select(sample, biosample1) %>% 
  unique()

donor_communities <- e0029 %>%
  filter(biosample2 != "blank", 
         biosample2 != "B-mix",
         !grepl("\\+", biosample2)) %>%
  pull(biosample2) %>%
  unique()

# join sample1 metadata and check
e0026_e0029_beta_1 <- beta_diversity_wide %>%
  left_join(e0026_filtered, by = c("sample1" = "sample")) %>% 
  filter(biosample1 %in% recipients)

# if the columns exist, rename them
e0026_e0029_beta_1 <- e0026_e0029_beta_1 %>%
    dplyr::rename(
      component1 = biosample1
    )

# Join sample2 metadata
e0026_e0029_beta_final <- e0026_e0029_beta_1 %>%
  left_join(e0026_filtered, by = c("sample2" = "sample")) %>% 
  filter(biosample1 %in% donor_communities)


# Rename columns to have biosample1 and biosample
e0026_e0029_beta_final <- e0026_e0029_beta_final %>%
    dplyr::rename(
      biosample1 = component1,
      biosample2 = biosample1
    )


```


### Define a function to extract passage information from raw sample ID

```{r}

extract_passage <- function(x) {
  ifelse(
    str_detect(x, "-mix-"),
    NA_character_,
    str_extract(x, "-[A-Z]-[08]-[A-Z0-9]+") %>%
      str_extract("[08]")
  )
}

# Add passage extraction
e0026_e0029_beta_final <- e0026_e0029_beta_final %>%
  mutate(
    passage1 = extract_passage(sample1),
    passage2 = extract_passage(sample2)
  ) %>% 
  filter(passage1 == 8, passage1 == passage2)

e0026_e0029_beta_final <- e0026_e0029_beta_final %>% 
  select(-passage1, -passage2, -bray, -jaccard) %>% 
  mutate(mixture = paste(biosample2, biosample1, sep = "+"))
  
```

**Plot distances**

```{r}

theme_set(theme_cowplot())

beta_diversity_mixture_plot <- ggplot(e0026_e0029_beta_final, aes(x = biosample2, y = biosample1, fill = jsd)) +
  geom_tile() +
  scale_fill_viridis_c(option = "A") +
  labs(x = "Donor", y = "Recipient", fill = "JSD",
       title = "JSD Heatmap Across Donor–Recipient Pairs")

ggsave(
  filename = file.path(OUTPUTDIR, "diversity_heatmap_plot.png"),
  plot = beta_diversity_mixture_plot,
  width = 10,
  height = 10,
  dpi = 600,
  bg = "white"
)

beta_diversity_mixture_plot


```





